### PR TITLE
Dash prettify

### PR DESCRIPTION
**Pull request by alvinwan**
- differentiating between assignment "status" and assignment "progress"
- HTML updated

New Version:
screen shot 2015-01-29 at 11 56 01 am

Old Version:
screen shot 2015-01-29 at 11 56 10 am

### CODE REVIEW

**Comment by Some3141** [comment]
Can it be colored green when the assignment is done?

**Comment by Sumukh** [comment]
What exactly does done mean here - that there is a submission and the assignment is inactive? 

It will already turn gray when the assignment is inactive.

**Comment by Some3141** [comment]
Sorry- I meant submitted. Basically, that way a student can just quickly scroll through and get a sense of whether or not they submitted.

**Comment by Sumukh** [comment]
:+1:

**Comment by alvinwan** [comment]
Gotcha. Green added and partial updated accordingly.

**Pull request merged**
