### PR TITLE
Submission Scores

### PR DESCRIPTION
**Pull request by alvinwan**
two updates:
- adds "submissions" button to all assignments, for easy access
- can get list of submissions via URL (not for direct use, for other code)
- submisisons list shows scores

summary gif:
submission scores

@Sumukh @soumyabasu ready.

### CODE REVIEW

**Comment by Sumukh** [comment]
It'd be good to more display more information about the score (like the tag (composition autograder etc) & time, maybe hovering could reveal the message)

**Comment by alvinwan** [comment]
Sure thing. I'll work on that. Can I stuff all of that inside of a little blurb on hover?

**Comment by Sumukh** [comment]
We should display the source (composition) with the score - but everything else can be on hover (or click)

**Comment by alvinwan** [comment]
submissions-details

@Sumukh @soumyabasu Ready.

**Pull request merged**
