### PR TITLE
Stream submissions to zipfile

### LINKED ISSUE #597: Submission Export Encoding Error
I tried to export submissions for the other course using ok and keep getting (a variety) of errors. 

```
    E 18:51:22.586 'ascii' codec can't encode character u'\u2212' in position 4614: ordinal not in range(128)
      Traceback (most recent call last):
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
          rv = self.handle_exception(request, response, e)
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
          rv = self.router.dispatch(request, response)
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
          return route.handler_adapter(request, response)
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
          return handler.dispatch()
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
          return self.handle_exception(e, self.app.debug)
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
          return method(*args, **kwargs)
        File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 310, in post
          self.run_from_request()
        File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 305, in run_from_request
          run(self.request.body)
        File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 147, in run
          return func(*args, **kwds)
        File "/base/data/home/apps/s~ok-server/1.387324334233159580/app/utils.py", line 615, in subms_to_gcs
          zipfile = add_subm_to_zip(subm, Submission, zipfile, result)
        File "/base/data/home/apps/s~ok-server/1.387324334233159580/app/utils.py", line 560, in add_subm_to_zip
          return add_to_zip(zipfile, file_contents, name)
        File "/base/data/home/apps/s~ok-server/1.387324334233159580/app/utils.py", line 122, in add_to_zip
          zipfile.writestr(join(dir, filename), contents)
        File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/zipfile.py", line 1220, in writestr
          zinfo.CRC = crc32(bytes) & 0xffffffff       # CRC-32 checksum
      UnicodeEncodeError: 'ascii' codec can't encode character u'\u2212' in position 4614: ordinal not in range(128)
    I 18:51:24.083 Full proto way too large to save, cleared frames.
```

### PR DESCRIPTION
**Pull request by knrafto**
Fixes #597

Deployed to staging, but I can't test on the new course: `Don't have permission to get unknown object`. Guess I'm only authorized for 61A. @Sumukh could you take a look?

### CODE REVIEW

**Comment by knrafto** [comment]
Didn't realize my commit was named so badly :fearful:

**Comment by knrafto** [comment]
If I go to prod [here](https://staging-dot-ok-server.appspot.com/manage#/course/5631829415559168/submissions/-assignment%20%22Hog%22) and hit download, I get `Required parameter 'query' not found`. Is this the way to export submissions?

**Comment by Sumukh** [comment]
Yeah - I can add you to that course. (staging is a bad name because it actually uses the prod database)

The search download is a little weird   - I'll take a look soon.

**Comment by Sumukh** [comment]
Alright - yeah it seems that the download is available after waiting for the query to return (which might take a while - or never return if > 10 minutes). 

There's a name error - you can check the logs at the log page on the console. (filter to the staging module & show errors only) 

        File "/base/data/home/apps/s~ok-server/staging.387409714099455112/app/utils.py", line 608, in subms_to_gcs
          with contextlib.closing(gcs_file) as f:
      NameError: global name 'contextlib' is not defined

**Comment by knrafto** [comment]
Okay, currently it shouldn't wait for that query to complete before trying to make the zip file, so there's something else going on. I'll look into it this weekend

**Comment by knrafto** [comment]
Woo, downloaded all 3212 Hog submissions. Closing this and making a new PR, partially so I can rename the remote branch.

**Pull request closed without merging**
