### PR TITLE
Cross-platform, cross-browser compatibility and Bootstrap Update

### LINKED ISSUE #434: Composition/FinalSubmission Broken on Master
The following traceback occurs on master when trying to view a diff. This may actually show up in other places too. 

The master branch hasn't been deployed - so we're okay for now.

```
Traceback (most recent call last):
  File "/Users/sumukh/Dropbox/CS61A/ok/server/app/urls.py", line 201, in api_wrapper
    rval = view(*args, **kwds)
  File "/Users/sumukh/Dropbox/CS61A/ok/server/gaenv/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/sumukh/Dropbox/CS61A/ok/server/app/api.py", line 226, in dispatch_request
    is_index=(method_name == 'index'))
  File "/Users/sumukh/Dropbox/CS61A/ok/server/app/api.py", line 204, in call_method
    return method(user, data)
  File "/Users/sumukh/Dropbox/CS61A/ok/server/app/api.py", line 364, in index
    result = self.model.can(user, need, query=query)
  File "/Users/sumukh/Dropbox/CS61A/ok/server/app/models.py", line 118, in can
    return cls._can(user, need, obj, query)
  File "/Users/sumukh/Dropbox/CS61A/ok/server/app/models.py", line 1169, in _can
    user, need, final.submission.get() if final else None, query)
  File "/Users/sumukh/Dropbox/CS61A/ok/server/app/models.py", line 768, in _can
    return Backup._can(user, need, submission.backup.get(), query)
AttributeError: 'NoneType' object has no attribute 'backup'
```

### PR DESCRIPTION
**Pull request by alvinwan**
<strike>**Note:** To "merge," `reset --hard` to commit 77d0a7a29533d9212a535525fbc6394193737dce and rebase this branch onto master.</strike>

**Critical fixes**
* <strike>resolves the admin code-loading bug, by resetting to commit 77d0a7a29533d9212a535525fbc6394193737dce and rebasing all branch-specific commits over</strike>
* resolves line number and comment issues, by using the admin code viewer -- fixes #434 

**Noteworthy fixes**
* font converted to Roboto for readability (Raleway, Open Sans too thin)
* page structure setup with Bootstrap framework
* eliminated all jQuery (integrated into angular JS files)
* checked for compatibility with Firefox, Chrome -- developed on Safari
* checked for compatibility with larger screens, tablets -- mobile needs testing

**Other Updates**
- tour updated to match new design, although user flow is identical
- adds ability for students to reply to reader comments (Students can also add new comments. There's no point - should we specifically prevent this?)
- prepares front-end for FlagSubmission endpoint

**Screenshots**

Course Landing
screen shot 2015-04-25 at 11 16 52 pm

Course Page
screen shot 2015-04-25 at 11 17 02 pm

Assignment Detail
screen shot 2015-04-25 at 11 17 11 pm

Persistent Menu
screen shot 2015-04-25 at 11 17 22 pm

Submission, Diff View
screen shot 2015-04-25 at 11 17 45 pm

To-dos:
- <strike>(!) reload view after accepting and issuing invitations</strike>
- add highlight functionality for blobs
- write short pattern generator to accommodate vertical/horizontal blobs
- <strike>fix blurred header in submission view</strike>

### CODE REVIEW

**Comment by alvinwan** [comment]
@Sumukh Thanks for all your help lolol xD

**Comment by Sumukh** [comment]
This looks awesome - great work! :hand:   

I will take a look soon! we probably won't be able to deploy this for a little while - until some other things are wrapped up.

**Comment by soumyabasu** [comment]
We shouldn't deploy this until the summer- I don't want to change things up on everyone right before the end of the semester.

It looks really pretty though. :)

**Comment by alvinwan** [comment]
@Sumukh @soumyabasu Sounds good. Thanks!

**Comment by Sumukh** [comment]
Some issues: 

- occasionally the blur on the header sticks around for too long and stays blurred. (try to click on a view submission link from the sidebar) 
-  the color on the side view differs from the color of the block (i.e, the preview will be yellow but the sidebar is green) 
- once you are in the detail sidebar view - clicking outside of the modal should close the detail view

**Comment by alvinwan** [comment]
@Sumukh Awesome! Just finished fixes. I skipped highlighting blobs for now - not critical and I still have parts to figure out:

- blurred header fixed
- color between blobs and sidebar unified
- clicking outside modal closes sidebar (there was a bug - I squashed it)
- accept/reject invites now clarified with message (and view reload)
- tour is now fully responsive

**Comment by alvinwan** [comment]
@Sumukh Is this ready to merge?

**Comment by Sumukh** [comment]
More issues:
- invite weirdness  (To replicate login as test@example.com and invite student0@student.com) 

image

Also - I'm logged in as student0 - I shouldn't have an option to accept/reject that - perhaps its displaying the wrong email? 

- after any change - the detail window disappears and the page is blurred. 

Also these calls might be leftover from the previous version - they are causing JS errors. 
TypeError: $scope.hideLoader is not a function
TypeError: $scope.hidePopups is not a function

**Comment by alvinwan** [comment]
@Sumukh 

- Yeah, that was in a previous iteration. Try pulling again.
- If test@example.com invites student0@teamwork.com, though, why wouldn't student0 be able to accept/reject the invite?
- I'm not able to replicate these errors... pull again? (tried it on Chrome, Safari, and Firefox) Let me know if the error still comes up.

**Comment by Sumukh** [comment]
Re Invite: 
- I see. The student should be able to accept/reject - however - they should also be able to see who invited them. 

Here's my suggestion: We can fix this by just displaying the existing members of the group already (and just making the box for the current user say: Respond to invitation | :white_check_mark: | :x:

**Comment by alvinwan** [comment]
@Sumukh 
Invite: Good point. Took your suggestion and here's what it looks like now (for the invited user):

screen shot 2015-06-14 at 5 46 02 pm


Reload: After accepting/rejecting, the modal should close, show an alert and refresh. I just double-checked and inviting the member also triggers a modal refresh. Is there something else I'm forgetting? It was kind of a patchy process, so I  might've missed some other scenario.

Green: Ah okay. I removed it for now, and added a purple color scheme option instead.

**Comment by Sumukh** [comment]
Almost ready to merge - feel free to merge once these are taken care of: 

- Investigate: Use the results of the more submissions 
- Integrate: Mark submission as final ($scope.changeSubmission) 

Another 
- Minor: Responsiveness bug with the logo at < 600px (CSS rules)
- Minor: The blur/loading bar is a little weird on the view code page - but this is not really worth spending time on now.

**Pull request merged**
