### PR TITLE
Enhancement/sumukh/final subm api

### PR DESCRIPTION
**Pull request by monicagangwar**
Fixed typo and resolved merge conflicts
Need some basic info to update the documentation 
#917

### CODE REVIEW

**Comment by Sumukh** [comment]
Thanks. Do you think you could add a test & some documentation?

Here's an example of what files should be changed & how to write a test: 

https://github.com/Cal-CS-61A-Staff/ok/pull/888/files

**Comment by monicagangwar** [comment]
certainly. give me a day

**Comment by monicagangwar** [comment]
@Sumukh Existing tests are already failing, can you look into it ? so that when i write my own tests, i could debug.

**Comment by Sumukh** [comment]
@monicagangwar  - The tests are failing because ExportBackup, ExportFinal are redefined - checkout line 915 of api.py 

image

**Comment by Sumukh** [comment]
@monicagangwar - #928 has a working version of the API. If you've worked on the tests for this route - that would still be a useful contribution that we could merge :)

**Comment by monicagangwar** [comment]
@Sumukh Hi, didn't get a chance to work on this yet. Give me a day more i'll add the tests

**Comment by Sumukh** [comment]
Sure - no problem. 

You might want to file a new PR that merges into: enhancement/sumukh/final_subm_api

**Comment by monicagangwar** [comment]
@Sumukh raised the PR here #932

**Comment by Sumukh** [comment]
Closing due to this route being implemented in #783 and the new PR open for the test

**Pull request closed without merging**
