### PR TITLE
[WiP] New landing page

### PR DESCRIPTION
**Pull request by kevinlin1**
landing-demo

### CODE REVIEW

**Comment by Sumukh** [comment]
Nice! What are the changes you'd like to make? 

There's some copy we need to add. I like your selection of screenshots.

**Comment by Sumukh** [comment]
Current Status: 
2016-10-27-23-21-localhost-5000

**Comment by Sumukh** [comment]
We can add the testimonials back in once we have something to put in there. 

This PR LGTM - feel free to merge it if you think it's ready. We can continue to ship improvements as we go.

**Comment by knrafto** [comment]
I have some small editorial nitpicks. I'm leaving a comment instead of making changes so you have a change to reject my suggestions
  * "CS 61A" and "CS 168" are both two words
  * Is it "OK" or "Ok"? We should capitalize it consistently
  * "Used by many courses" to me seems a bit...off. Since there's a list right after it, "Used by courses with millions of submissions" might be fine
  * Don't capitalize "Computer Science" in the last block
  * "With a language agnostic autograder - you can..." -> "With a language agnostic autograder, you can..." -> 
  * "Give personalized feedback" -> "Personalized feedback" since the rest of the "feature" blocks are noun phrases
    * "composition" is pretty 61A specific. "style" would be a more familiar term

**Comment by knrafto** [comment]
All of our page titles use "Ok"

**Comment by Sumukh** [comment]
We're inconsistent on those titles - but I don't want to scope that into this PR.  I've commented on https://github.com/Cal-CS-61A-Staff/ok/issues/866

I think `OK` should be what we roll with for now since it matches the logotype.

**Comment by Sumukh** [comment]
I'm going to merge this - future improvements can be another PR.

**Pull request merged**
