### PR TITLE
Update final submissions

### PR DESCRIPTION
**Pull request by papajohn**

### CODE REVIEW

**Comment by papajohn** [comment]
Ok, making progress. We need some more tests to make sure final submissions are correct under many circumstances (leaving groups, etc.), but at least #331 should be fixed.

**Comment by Sumukh** [comment]
@moowiz - Is this okay to deploy?

**Comment by Sumukh** [comment]
@moowiz - Is this ready to deploy? I think this will fix another issue with the API.

**Comment by moowiz** [comment]
LGTM. Looks like he fixed the bug!

**Comment by Sumukh** [comment]
There might still be issues - I'm trying to fix them - here's what I have so far. I'll keep working on this branch. 

Changelog: 
1. Fixed key vs obj in queries 
2. `latest.group = group.key` - account for group being none 
3. final.key.delete()
4. edit final submission pre_put_hook (see fix_final branch) 
5. We also need to call update_final_submission on the first user who sent the invite because it currently shows No Submission after the invite - but it appears after the other user accepts the invite

**Pull request merged**
