### PR TITLE
Editing Assignment through Dashboard

### PR DESCRIPTION
**Pull request by alvinwan**
"Edit" button and functionality added.

site-edit-assign

### CODE REVIEW

**Comment by Sumukh** [comment]
Can you also add fields for the lock date and the resubmission boolean?

**Comment by alvinwan** [comment]
I just added the lock date and revision fields. What does it mean to have a template for an assignment? An HTML file?

**Comment by Sumukh** [comment]
We need templates to render a diff between a students submission and the starting file that we provide (i.e a hog.py without student code”) 

It’s worth noting that there can be multiple template files (scheme project for example) 

-- 
Sumukh Sridhara

On June 17, 2015 at 3:59:29 PM, Alvin Wan (notifications@github.com) wrote:

I just added the lock date and revision fields. What does it mean to have a template for an assignment? An HTML file?

**Comment by alvinwan** [comment]
I added the upload field; it allows multiple files.

**Comment by alvinwan** [comment]
The changes to the Assignment API for templates have been reverted. I'm stumped.

**Comment by Sumukh** [comment]
Ok merging - but we should figure out templates in #451

**Pull request merged**
