### PR TITLE
Submission search should find assignments in same course

### PR DESCRIPTION
**Pull request by knrafto**
Previously, searching for submissions for fa15 Ants was broken, because it takes the first assignment named "Ants", which happened to be a previous semester's Ants project.

Tested on staging

### CODE REVIEW

**Comment by knrafto** [comment]
Oops, forgot to ./run_tests

**Comment by Sumukh** [comment]
Aside from the broken tests it looks good to me

**Comment by knrafto** [comment]
@alvinwan ready to merge!
I need this for Ants regrades - I'll just use the staging version for now.

**Comment by alvinwan** [comment]
LGTM. Merging.

**Pull request merged**
