### PR TITLE
fixes comp loading bug

### PR DESCRIPTION
**Pull request by alvinwan**
@Sumukh @soumyabasu REady.

#538

### CODE REVIEW

**Comment by soumyabasu** [comment]
Travis looks like it's failing.

**Comment by soumyabasu** [comment]
It looks like the status bug.

**Comment by alvinwan** [comment]
Yeah, it's the status bug.

**Comment by Sumukh** [comment]
I have another fix that doesn't break student-side code. Closing for now.

**Comment by alvinwan** [comment]
Wait, hold on. I'm fixing `get_submissions`.

**Comment by Sumukh** [comment]
Ok - composition grading seems to work again.

**Pull request merged**
