### PR TITLE
v2: Give permissions on GCS file to requester

### PR DESCRIPTION
**Pull request by LuiseV**
Gives the user who requests the score export OWNER access to the cloud storage score file.

### CODE REVIEW

**Comment by Sumukh** [comment]
Tests are failing because of `AssertionError: No api proxy found for service "memcache"`

**Comment by LuiseV** [comment]
I can look at it tomorrow (Europe time :) )

**Comment by Sumukh** [comment]
For future reference in case we do need the tests to pass: 

The tests pass when the stubs are registered `utils.py`
```
from google.appengine.api import apiproxy_stub_map
from google.appengine.api.memcache import memcache_stub
from google.appengine.api.app_identity import app_identity_stub
apiproxy_stub_map.apiproxy.RegisterStub('memcache', memcache_stub.MemcacheServiceStub())
apiproxy_stub_map.apiproxy.RegisterStub('app_identity_service', app_identity_stub.AppIdentityServiceStub())
```
A hack would be to do something like `if os.env(flask_conf) == "test": ...`. (though there's almost certainly a better fix)

**Comment by Sumukh** [comment]
Closing due to v3 being the master branch now. 

Someday we'll figure out how to make the test suite pass with this code...

**Pull request closed without merging**
