### PR TITLE
Autograde UI [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by alvinwan**
Sumukh's suggestions

- [x] Grade Final Submissions button -- *in course assignments next to each assignment*
- [x] Provide zip file URL with the starter code -- *part of assignment creation/edit*
- [x] Customize the grading script (which is just bash) here’s where you could download additional tests and do any additional setup. -- *part of assignment creation/edit*
- [ ] Hit done - you’ll be sent to a queue status page (here’s where you could cancel the queue, see the status etc) - the grades will pour in.

### CODE REVIEW

**Comment by alvinwan** [comment]
@Sumukh Is there supposed to be one "autograde" button for all assignments? I placed on "auto grade" button for each assignment in the course assignments list.

**Comment by albert12132** [comment]
An autograde button for individual submissions would be useful too, so that
staff members can facilitate regrade requests.

**Comment by Sumukh** [comment]
In addition I need three/four fields on the assignment. 

- Autograding enabled (boolean)
- Grading Script file (as a string) 
- Zip File URL  (string)
- Access Token field (string)

Could you add these fields to the Assignment model and to the assignment creation/editing pages?

**Comment by alvinwan** [comment]
@albert12132 Good idea. Will add.
@Sumukh On it.

**Comment by alvinwan** [comment]
@Sumukh Is the grading script "file field" actually a string containing the file's contents?

**Comment by Sumukh** [comment]
@alvinwan  - yes but its been implemented in the other branch. 

Closing because this is already in the other branch. Let's work in enhancement/sumukh/autograding_v2

**Comment by alvinwan** [comment]
@Sumukh sounds good.

**Pull request closed without merging**
