### PR TITLE
Status Checks

### PR DESCRIPTION
**Pull request by alvinwan**
remaining tests and modifications to `user.status` commented

### CODE REVIEW

**Comment by Sumukh** [comment]
Changes to participant.status should also be removed. 

I'd be ok with just removing the code instead of commenting it out.

**Comment by alvinwan** [comment]
*Status fields removed.

**Comment by soumyabasu** [comment]
Is this good to go? It's causing our build to break.

**Comment by alvinwan** [comment]
Yep, it's good to go if you two are good with it.

**Pull request merged**
