### PR TITLE
Better Email Check

### PR DESCRIPTION
**Pull request by addcninblue**
It wasn't in the issue tracker, but it was listed as a TODO (discovered while I was looking at issue #1173). Please let me know if this pull request was done wrong (because I'm not sure how pr's work when I'm 4 commits ahead of 61a/ok)

Thanks

### CODE REVIEW

**Comment by Sumukh** [comment]
Looks good. Let's be sure to use github's squash and merge when merging this in.

re: 
> (because I'm not sure how pr's work when I'm 4 commits ahead of 61a/ok)

This is fine, but ideally the PR would just contain the latest commit (38ab101). This post has some tips on how you can do that: https://spin.atomicobject.com/2017/04/23/maintain-clean-git-history/

**Comment by Sumukh** [comment]
Note that CircleCI is not going to pass since this was a PR from an external repo. Someone should re-evaluate if we really need the protected branch or if CircleCI really needs to be configured to not run external PRs

**Comment by colinschoen** [comment]
Any reason CircleCi should not run on external PRs?

**Comment by epai** [comment]
hmm, can you try making this change off of the `epai/grading_export` branch?  I made a bunch of changes to how csvs are validated.  see #1212

**Pull request merged**
