### PR TITLE
Add instruction on how to run workers

### LINKED ISSUE #1175: Add instructions for starting rq workers
How to run jobs using rq workers is not documented anywhere, apparently.  We should add a small bit to the README with instructions for how to install redis, and that they can run a worker with `./manage.py worker`

### PR DESCRIPTION
**Pull request by jezeniel**
This will close #1175

### CODE REVIEW

**Comment by jezeniel** [comment]
@colinschoen any tips to do this? there a lots of platform or should we focus on only one like ubuntu?

**Comment by colinschoen** [comment]
Ah, let's just provide a link to here:

https://redis.io/topics/quickstart

That should be enough.

**Comment by jezeniel** [comment]
@colinschoen i added the changes. i squashed the commit for your review.

**Comment by colinschoen** [comment]
Can you try pushing one more commit. It can just be a space or word change. It looks like circleci is timing out. Pushing another commit should trigger it once more.

**Comment by jezeniel** [comment]
i think there is a problem with circle ci.

**Comment by colinschoen** [comment]
Fixed in #1198.

Will merge this after.

**Pull request merged**
